name: server

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - server/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: linereats
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
    - name: Deploy with Cloud Run
      run: |
        cd server
        gcloud components install beta
        gcloud beta run deploy server --project linereats --source . --concurrency 100 --platform managed --region us-central1 --memory 512Mi
